SERIES = [{'competition_id': 133348, 'name': 'Allsvenskan', 'gender': 'Herr'},
 {'competition_id': 133340, 'name': 'Superettan', 'gender': 'Herr'},
 {'competition_id': 133338, 'name': 'Ettan Norra', 'gender': 'Herr'},
 {'competition_id': 133339, 'name': 'Ettan Södra', 'gender': 'Herr'},
 {'competition_id': 133440, 'name': 'OBOS Damallsvenskan', 'gender': 'Dam'},
 {'competition_id': 133439, 'name': 'Elitettan', 'gender': 'Dam'},
 {'competition_id': 131955, 'name': 'Div 2 Norra Svealand', 'gender': 'Herr'},
 {'competition_id': 131956, 'name': 'Div 2 Södra Svealand', 'gender': 'Herr'},
 {'competition_id': 131957, 'name': 'Div 2 Norra Götaland', 'gender': 'Herr'},
 {'competition_id': 131958, 'name': 'Div 2 Södra Götaland', 'gender': 'Herr'},
 {'competition_id': 131959, 'name': 'Div 2 Västra Götaland', 'gender': 'Herr'},
 {'competition_id': 131960, 'name': 'Div 2 Norrland Vår Norra', 'gender': 'Herr'},
 {'competition_id': 131961, 'name': 'Div 2 Norrland Vår Södra', 'gender': 'Herr'},
 {'competition_id': 131962, 'name': 'Div 2 Norrland Höst Uppflyttning', 'gender': 'Herr'},
 {'competition_id': 131963, 'name': 'Div 2 Norrland Höst Nedflyttning', 'gender': 'Herr'},
 {'competition_id': 136305, 'name': 'Dam div 5', 'gender': 'Dam'},
 {'competition_id': 131926, 'name': 'Damer 3 A', 'gender': 'Dam'},
 {'competition_id': 131927, 'name': 'Damer 3 B', 'gender': 'Dam'},
 {'competition_id': 131928, 'name': 'Damer 4 A', 'gender': 'Dam'},
 {'competition_id': 131929, 'name': 'Damer 4 B', 'gender': 'Dam'},
 {'competition_id': 131930, 'name': 'Damer 5 A', 'gender': 'Dam'},
 {'competition_id': 131931, 'name': 'Damer 5 B', 'gender': 'Dam'},
 {'competition_id': 136367, 'name': 'Damer Div. 3', 'gender': 'Dam'},
 {'competition_id': 135521, 'name': 'Damer, Div 2 Nordvästra Götaland', 'gender': 'Dam'},
 {'competition_id': 135587, 'name': 'Damer, Div 3 Norra', 'gender': 'Dam'},
 {'competition_id': 135586, 'name': 'Damer, Div 3 Södra', 'gender': 'Dam'},
 {'competition_id': 135588, 'name': 'Damer, Div 4 Södra', 'gender': 'Dam'},
 {'competition_id': 135589, 'name': 'Damer, Div 4 Västra', 'gender': 'Dam'},
 {'competition_id': 135590, 'name': 'Damer, Div 4 Östra', 'gender': 'Dam'},
 {'competition_id': 135591, 'name': 'Damer, Div 5 Söder', 'gender': 'Dam'},
 {'competition_id': 135592, 'name': 'Damer, Div 5 Västra', 'gender': 'Dam'},
 {'competition_id': 135593, 'name': 'Damer, Div 5 Östra', 'gender': 'Dam'},
 {'competition_id': 131965, 'name': 'Div 1 Mellersta, dam 2026', 'gender': 'Dam'},
 {'competition_id': 131964, 'name': 'Div 1 Norra, dam 2026', 'gender': 'Dam'},
 {'competition_id': 131966, 'name': 'Div 1 Södra, dam 2026', 'gender': 'Dam'},
 {'competition_id': 135153, 'name': 'Div 2 Norra Norrland Nord Damer', 'gender': 'Dam'},
 {'competition_id': 132034, 'name': 'Div 2 NÖ Götaland Dam', 'gender': 'Dam'},
 {'competition_id': 134074, 'name': 'Div 2 Västra Svealand damer 2026', 'gender': 'Dam'},
 {'competition_id': 135624, 'name': 'Div 3 Damer 2026 Medelpad', 'gender': 'Dam'},
 {'competition_id': 132035, 'name': 'Div 3 NV Dam', 'gender': 'Dam'},
 {'competition_id': 132037, 'name': 'Div 3 SV Dam', 'gender': 'Dam'},
 {'competition_id': 132036, 'name': 'Div 3 SÖ Dam', 'gender': 'Dam'},
 {'competition_id': 133889, 'name': 'Div 3 Värmland damer 2026', 'gender': 'Dam'},
 {'competition_id': 136281, 'name': 'Div 3. Damer', 'gender': 'Dam'},
 {'competition_id': 132038, 'name': 'Div 4 NV Dam', 'gender': 'Dam'},
 {'competition_id': 132039, 'name': 'Div 4 NÖ Dam', 'gender': 'Dam'},
 {'competition_id': 132041, 'name': 'Div 4 SV Dam', 'gender': 'Dam'},
 {'competition_id': 132040, 'name': 'Div 4 SÖ Dam', 'gender': 'Dam'},
 {'competition_id': 136162, 'name': 'Div 4 norra damer 2026', 'gender': 'Dam'},
 {'competition_id': 136163, 'name': 'Div 4 södra damer 2026', 'gender': 'Dam'},
 {'competition_id': 132043, 'name': 'Div 5 Höglandet Dam', 'gender': 'Dam'},
 {'competition_id': 132042, 'name': 'Div 5 JKPG Dam', 'gender': 'Dam'},
 {'competition_id': 132045, 'name': 'Div 5 Kalmar/Öland Dam', 'gender': 'Dam'},
 {'competition_id': 132044, 'name': 'Div 5 Vimmerby Dam', 'gender': 'Dam'},
 {'competition_id': 132047, 'name': 'Div 5 Värnamo Dam', 'gender': 'Dam'},
 {'competition_id': 132046, 'name': 'Div 5 Växjö Dam', 'gender': 'Dam'},
 {'competition_id': 133438, 'name': 'Div.2 Damer Mellersta Norrland 2026', 'gender': 'Dam'},
 {'competition_id': 135343, 'name': 'Div.3 Dam Bohuslän-Dalsland 2026', 'gender': 'Dam'},
 {'competition_id': 136129, 'name': 'Div.4 Dam Bohuslän-Dalsland', 'gender': 'Dam'},
 {'competition_id': 133529, 'name': 'Division 2 Dam M Svealand', 'gender': 'Dam'},
 {'competition_id': 131779, 'name': 'Division 2 Dam Norra Norrland Syd', 'gender': 'Dam'},
 {'competition_id': 135358, 'name': 'Division 2 Dam Sydvästra Götaland', 'gender': 'Dam'},
 {'competition_id': 133317, 'name': 'Division 2 Dam Sydöstra Götaland', 'gender': 'Dam'},
 {'competition_id': 135294, 'name': 'Division 2 Dam Södra Norrland', 'gender': 'Dam'},
 {'competition_id': 133541, 'name': 'Division 2 Damer Östra Svealand', 'gender': 'Dam'},
 {'competition_id': 133158, 'name': 'Division 3 Dam', 'gender': 'Dam'},
 {'competition_id': 133244, 'name': 'Division 3 Dam Dalarna', 'gender': 'Dam'},
 {'competition_id': 135531, 'name': 'Division 3 Dam Gestrikland', 'gender': 'Dam'},
 {'competition_id': 133915, 'name': 'Division 3 Dam Halland', 'gender': 'Dam'},
 {'competition_id': 135298, 'name': 'Division 3 Dam J/H', 'gender': 'Dam'},
 {'competition_id': 133196, 'name': 'Division 3 Dam Södermanland', 'gender': 'Dam'},
 {'competition_id': 133311, 'name': 'Division 3 Dam Södra Skåne', 'gender': 'Dam'},
 {'competition_id': 133877, 'name': 'Division 3 Dam Uppland', 'gender': 'Dam'},
 {'competition_id': 136471, 'name': 'Division 3 Dam VFF/ÖLFF', 'gender': 'Dam'},
 {'competition_id': 133309, 'name': 'Division 3 Dam Västra', 'gender': 'Dam'},
 {'competition_id': 133928, 'name': 'Division 3 Dam Ångermanland', 'gender': 'Dam'},
 {'competition_id': 136333, 'name': 'Division 3 Dam Östergötland', 'gender': 'Dam'},
 {'competition_id': 133310, 'name': 'Division 3 Dam Östra Skåne', 'gender': 'Dam'},
 {'competition_id': 131776, 'name': 'Division 3 dam grp 1', 'gender': 'Dam'},
 {'competition_id': 131777, 'name': 'Division 3 dam grp 2', 'gender': 'Dam'},
 {'competition_id': 134081, 'name': 'Division 4 Dam', 'gender': 'Dam'},
 {'competition_id': 136282, 'name': 'Division 4 Dam Halland', 'gender': 'Dam'},
 {'competition_id': 133314, 'name': 'Division 4 Dam Mellersta Skåne', 'gender': 'Dam'},
 {'competition_id': 133312, 'name': 'Division 4 Dam Nordvästra Skåne', 'gender': 'Dam'},
 {'competition_id': 133313, 'name': 'Division 4 Dam Nordöstra Skåne', 'gender': 'Dam'},
 {'competition_id': 133242, 'name': 'Division 4 Dam Norra Dalarna', 'gender': 'Dam'},
 {'competition_id': 133315, 'name': 'Division 4 Dam Sydvästra A Skåne', 'gender': 'Dam'},
 {'competition_id': 133927, 'name': 'Division 4 Dam Sydvästra B Skåne', 'gender': 'Dam'},
 {'competition_id': 136332, 'name': 'Division 4 Dam Södermanland', 'gender': 'Dam'},
 {'competition_id': 133243, 'name': 'Division 4 Dam Södra Dalarna', 'gender': 'Dam'},
 {'competition_id': 133316, 'name': 'Division 4 Dam Södra Skåne', 'gender': 'Dam'},
 {'competition_id': 133878, 'name': 'Division 4 Dam Uppland', 'gender': 'Dam'},
 {'competition_id': 133720, 'name': 'Division 4 Dam Västmanland', 'gender': 'Dam'},
 {'competition_id': 135617, 'name': 'Division 4 Dam Örebro', 'gender': 'Dam'},
 {'competition_id': 136335, 'name': 'Division 4 Västra Dam Östergötland', 'gender': 'Dam'},
 {'competition_id': 136334, 'name': 'Division 4 Östra Dam Östergötland', 'gender': 'Dam'},
 {'competition_id': 133160, 'name': 'Division 4A Dam', 'gender': 'Dam'},
 {'competition_id': 133161, 'name': 'Division 4B Dam', 'gender': 'Dam'},
 {'competition_id': 136244, 'name': 'Division 5 Dam', 'gender': 'Dam'},
 {'competition_id': 136336, 'name': 'Division 5 Dam Östergötland', 'gender': 'Dam'},
 {'competition_id': 133198, 'name': 'Division 5A Dam', 'gender': 'Dam'},
 {'competition_id': 133950, 'name': 'Division 5B Dam', 'gender': 'Dam'}]
